# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addEntryGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.addEntryGroupBox.setObjectName("addEntryGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.addEntryGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addEntryGrid = QtWidgets.QGridLayout()
        self.addEntryGrid.setObjectName("addEntryGrid")
        self.urlInput = QtWidgets.QLineEdit(self.addEntryGroupBox)
        self.urlInput.setObjectName("urlInput")
        self.addEntryGrid.addWidget(self.urlInput, 0, 0, 1, 2)
        self.addButton = QtWidgets.QPushButton(self.addEntryGroupBox)
        self.addButton.setMinimumSize(QtCore.QSize(74, 62))
        self.addButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/ic_add_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setIconSize(QtCore.QSize(48, 48))
        self.addButton.setObjectName("addButton")
        self.addEntryGrid.addWidget(self.addButton, 0, 2, 2, 1)
        self.downloadLocationInput = QtWidgets.QLineEdit(self.addEntryGroupBox)
        self.downloadLocationInput.setMinimumSize(QtCore.QSize(0, 33))
        self.downloadLocationInput.setObjectName("downloadLocationInput")
        self.addEntryGrid.addWidget(self.downloadLocationInput, 1, 0, 1, 1)
        self.fileDialogInput = QtWidgets.QPushButton(self.addEntryGroupBox)
        self.fileDialogInput.setMinimumSize(QtCore.QSize(88, 31))
        self.fileDialogInput.setObjectName("fileDialogInput")
        self.addEntryGrid.addWidget(self.fileDialogInput, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.addEntryGrid)
        self.downloadItemGrid = QtWidgets.QGridLayout()
        self.downloadItemGrid.setSpacing(10)
        self.downloadItemGrid.setObjectName("downloadItemGrid")
        self.videoThumb = QtWidgets.QLabel(self.addEntryGroupBox)
        self.videoThumb.setMaximumSize(QtCore.QSize(48, 48))
        self.videoThumb.setBaseSize(QtCore.QSize(48, 48))
        self.videoThumb.setStyleSheet("border: 1px solid lightblue;")
        self.videoThumb.setText("")
        self.videoThumb.setObjectName("videoThumb")
        self.downloadItemGrid.addWidget(self.videoThumb, 0, 0, 2, 1)
        self.videoTitle = QtWidgets.QLabel(self.addEntryGroupBox)
        self.videoTitle.setObjectName("videoTitle")
        self.downloadItemGrid.addWidget(self.videoTitle, 0, 1, 1, 2)
        self.videoFormatSelector = QtWidgets.QComboBox(self.addEntryGroupBox)
        self.videoFormatSelector.setObjectName("videoFormatSelector")
        self.downloadItemGrid.addWidget(self.videoFormatSelector, 0, 3, 1, 2)
        self.videoAuthor = QtWidgets.QLabel(self.addEntryGroupBox)
        self.videoAuthor.setObjectName("videoAuthor")
        self.downloadItemGrid.addWidget(self.videoAuthor, 1, 1, 1, 1)
        self.videoViews = QtWidgets.QLabel(self.addEntryGroupBox)
        self.videoViews.setObjectName("videoViews")
        self.downloadItemGrid.addWidget(self.videoViews, 1, 2, 1, 1)
        self.videoDuration = QtWidgets.QLabel(self.addEntryGroupBox)
        self.videoDuration.setObjectName("videoDuration")
        self.downloadItemGrid.addWidget(self.videoDuration, 1, 3, 1, 1)
        self.videoDownloadSize = QtWidgets.QLabel(self.addEntryGroupBox)
        self.videoDownloadSize.setObjectName("videoDownloadSize")
        self.downloadItemGrid.addWidget(self.videoDownloadSize, 1, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.downloadItemGrid)
        self.verticalLayout_3.addWidget(self.addEntryGroupBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("background-color:  rgb(35, 94, 255)")
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 512, 258))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downloadListLayout = QtWidgets.QVBoxLayout()
        self.downloadListLayout.setObjectName("downloadListLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.downloadListLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.downloadListLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 23))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionVisit_us = QtWidgets.QAction(MainWindow)
        self.actionVisit_us.setObjectName("actionVisit_us")
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menuAbout.addAction(self.actionVisit_us)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addEntryGroupBox.setTitle(_translate("MainWindow", "Add link"))
        self.urlInput.setPlaceholderText(_translate("MainWindow", "Enter URL from YouTube"))
        self.addButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Download</p></body></html>"))
        self.downloadLocationInput.setPlaceholderText(_translate("MainWindow", "Download video to ..."))
        self.fileDialogInput.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select download location...</p></body></html>"))
        self.fileDialogInput.setText(_translate("MainWindow", "..."))
        self.videoTitle.setText(_translate("MainWindow", "Title"))
        self.videoAuthor.setText(_translate("MainWindow", "Author"))
        self.videoViews.setText(_translate("MainWindow", "Views"))
        self.videoDuration.setText(_translate("MainWindow", "Duration"))
        self.videoDownloadSize.setText(_translate("MainWindow", "Download size"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionVisit_us.setText(_translate("MainWindow", "Visit us"))

